name: 'translator'
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  translate:
    permissions:
      issues: write
      discussions: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/github-translate-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          IS_MODIFY_TITLE: true
          APPEND_TRANSLATION: true
